name: Create Tag
description: Create a version tag on a commit
inputs:
  use-latest:
    description: "Whether to add the latest tag too, default: true"
    required: false
    default: 'true'
    
branding:
  icon: 'tag'  
  color: 'orange'

runs:
  using: composite

  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.13
      with:
        versionSpec: "5.x"

    - name: Create GitVersion.yml
      run: |
        echo "mode: Mainline" > GitVersion.yml

    - name: Use GitVersion
      uses: gittools/actions/gitversion/execute@v0.9.13
      id: gitversion

    - run: |
        echo "NuGetVersionV2: ${{ steps.gitversion.outputs.fullSemVer }}"

    - name: Add Version Tag
      uses: rickstaa/action-create-tag@v1
      with:
        tag: v${{ steps.gitversion.outputs.fullSemVer }}
        force_push_tag: true
        github_token: ${{ github.token }}

    - name: Add latest Tag
      if: ${{ inputs.use-latest == 'true' }}
      uses: rickstaa/action-create-tag@v1
      with:
        tag: "latest"
        force_push_tag: true
        github_token: ${{ github.token }}
