name: Build and Test
description: Build and test a dotnet project
inputs:
  project-path:
    description: Path to the project or solution folder
    required: false
    default: ./src
  token:
    description: NuGet authentication token
    default: ${{ github.token }}
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: "6.0.x"

    - name: Prepare NuGet Source
      run: dotnet nuget add source --username klanggames --password ${{ inputs.token }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/klanggames/index.json"
      shell: bash

    - name: Restore
      shell: bash
      run: dotnet restore ${{ inputs.project-path }}

    - name: Build
      shell: bash
      run: dotnet build ${{ inputs.project-path }} --no-restore -c Release

    - name: Test
      shell: bash
      run: dotnet test ${{ inputs.project-path }} --logger trx --results-directory "${{ github.workspace }}/TestResults"

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-results
        path: ${{ github.workspace }}/TestResults
      if: ${{ always() }}
