name: Create Release
description: Create a new release and tag the commit
inputs:
  tag:
    description: Optional tag for the release. If no tag is provided the GitVersion semantic version will be used.
    required: false
    default: ''

runs:
  using: composite

  steps:
    - name: Checkout repository
      if: ${{ inputs.tag == '' }}
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup GitVersion
      if: ${{ inputs.tag == '' }}
      uses: klanggames/actions-shared-workflows/actions/setup-gitversion@v1
      id: gitversion

    - name: Create Release
      if: ${{ inputs.tag == '' }}
      uses: ncipollo/release-action@v1
      with:
        name: Release ${{ steps.gitversion.outputs.majorMinorPatch }}
        tag: v${{ steps.gitversion.outputs.majorMinorPatch }}
        generateReleaseNotes: true

    - name: Create Release
      if: ${{ inputs.tag != '' }}
      uses: ncipollo/release-action@v1
      with:
        name: Release ${{ inputs.tag }}
        tag: ${{ inputs.tag }}
        generateReleaseNotes: true
    
