name: Setup GitVersion
description: Install GitVersion and create default GitVersion.yml configuration
outputs:
  fullSemVer:
    description: "fullSemVer"
    value: ${{ steps.gitversion.outputs.fullSemVer }}
  majorMinorPatch:
    description: "majorMinorPatch"
    value: ${{ steps.gitversion.outputs.majorMinorPatch }}
  major:
    description: "major"
    value: ${{ steps.gitversion.outputs.major }}
  semVer:
    description: "semVer"
    value: ${{ steps.gitversion.outputs.semVer }}

runs:
  using: composite

  steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.15
      with:
        versionSpec: "5.x"

    - name: Create GitVersion.yml
      shell: bash
      run: |
        CONTENT=$(cat << EOF
        mode: Mainline
        branches:
          pull-request:
            regex: ^(pull|pull\-requests|pr)[/-]
            mode: Mainline
            tag: useBranchName
            increment: Inherit
            prevent-increment-of-merged-branch-version: false
            tag-number-pattern: '[/-](?<number>\d+)[-/]'
            track-merge-target: false
            source-branches: [ 'main', 'release', 'feature', 'support', 'hotfix' ]
            tracks-release-branches: false
            is-release-branch: false
            is-mainline: false
        EOF
        )
        echo "$CONTENT" > GitVersion.yml

    - name: Use GitVersion
      uses: gittools/actions/gitversion/execute@v0.9.15
      id: gitversion

    - run: |
        echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
      shell: bash
