name: Setup GitVersion
description: Install GitVersion and create default GitVersion.yml configuration
outputs:
  fullSemVer:
    description: "fullSemVer"
    value: ${{ steps.gitversion.outputs.fullSemVer }}

runs:
  using: composite

  steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.13
      with:
        versionSpec: "5.x"

    - name: Create GitVersion.yml
      shell: bash
      run: |
        echo "mode: Mainline" > GitVersion.yml

    - name: Use GitVersion
      uses: gittools/actions/gitversion/execute@v0.9.13
      id: gitversion

    - run: |
        echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
      shell: bash
