name: Dependabot Auto Merge
description: auto-merge Dependabot PRs
inputs:
  github-token:
    description: git hub token
    required: false
    default: ${{ github.token }}
  update-type:
    description: "type of update, default: version-update:semver-minor"
    default: version-update:semver-minor
    required: false

runs:
  using: composite
  steps:
    - name: Dependabot metadata
      id: metadata
      uses: dependabot/fetch-metadata@v1
      with:
        github-token: "${{ inputs.github-token }}"

    - name: Enable auto-merge for Dependabot PRs
      shell: bash
      if: steps.metadata.outputs.update-type == ${{ inputs.update-type }}
      run: gh pr merge --auto --merge "$PR_URL"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
