name: Create Tag
on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - ".devcontainer/**"
      - "**/README.md"

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup GitVersion
        uses: ./actions/setup-gitversion
        id: gitversion

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ steps.gitversion.outputs.majorMinorPatch }}
          tag: v${{ steps.gitversion.outputs.majorMinorPatch }}
          generateReleaseNotes: true

      - name: Add Version Tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: v${{ steps.gitversion.outputs.major }}
          force_push_tag: true
          github_token: ${{ github.token }}
