name: Create Tag
on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - ".devcontainer/**"
      - "**/README.md"

jobs:
  - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

  - name: Setup GitVersion
    uses: klanggames/actions-shared-workflows/actions/setup-gitversion@main
    id: gitversion

  - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: Release ${{ steps.gitversion.outputs.majorMinorPatch }}
        tag_name: v${{ steps.gitversion.outputs.majorMinorPatch }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}